apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  creationTimestamp: "2023-02-03T00:59:00Z"
  generation: 44
  labels:
    version: v3.3.1
  name: ks-installer
  namespace: kubesphere-system
  resourceVersion: "36898429"
  uid: 491ad68b-4588-4fcd-b84a-fa3439485f9c
spec:
  alerting:
    enabled: false
  auditing:
    enabled: false
  authentication:
    jwtSecret: ""
    authenticateRateLimiterMaxTries: 20
    authenticateRateLimiterDuration: 5m0s
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    es:
      basicAuth:
        enabled: false
        password: ""
        username: ""
      data:
        volumeSize: 20Gi
      elkPrefix: logstash
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
      logMaxAge: 7
      master:
        volumeSize: 4Gi
    gpu:
      kinds:
        - default: true
          resourceName: nvidia.com/gpu
          resourceType: GPU
    minio:
      volumeSize: 20Gi
    monitoring:
      GPUMonitoring:
        enabled: true
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
    openldap:
      enabled: true
    redis:
      enabled: false
  devops:
    enabled: true
    jenkinsJavaOpts_MaxRAM: 4g
    jenkinsJavaOpts_Xms: 1200m
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsMemoryLim: 4Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
  edgeruntime:
    enabled: false
    kubeedge:
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubHttpsNodePort: "30002"
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
      enabled: false
      iptables-manager:
        enabled: true
        mode: external
  etcd:
    endpointIps: 192.168.50.153
    monitoring: false
    port: 2379
    tlsEnable: true
  events:
    enabled: true
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: false
  monitoring:
    gpu:
      nvidia_dcgm_exporter:
        enabled: true
    node_exporter:
      port: 9100
    storageClass: ""
  multicluster:
    clusterRole: none
  network:
    ippool:
      type: none
    networkpolicy:
      enabled: false
    topology:
      type: true
  openpitrix:
    store:
      enabled: false
  persistence:
    storageClass: ""
  servicemesh:
    enabled: false
    istio:
      components:
        cni:
          enabled: false
        ingressGateways:
          - enabled: false
            name: istio-ingressgateway
  terminal:
    timeout: 600
status:
  clusterId: 32da9d16-bc20-477d-8d55-9b541c6bdc34-1675388932
  core:
    enabledTime: 2023-02-03T03:22:34GMT
    status: enabled
    version: v3.3.1
  devops:
    enabledTime: 2023-02-03T03:29:08GMT
    status: enabled
  es:
    enabledTime: 2023-02-03T01:45:47GMT
    status: enabled
  events:
    enabledTime: 2023-02-03T01:47:20GMT
    status: enabled
  fluentbit:
    enabledTime: 2023-02-03T01:45:52GMT
    status: enabled
  logging:
    enabledTime: 2023-02-03T01:47:25GMT
    status: enabled
  minio:
    enabledTime: 2023-02-03T01:45:43GMT
    status: enabled
  monitoring:
    enabledTime: 2023-02-03T03:23:58GMT
    status: enabled
  openldap:
    enabledTime: 2023-02-03T01:45:38GMT
    status: enabled
